### ISSUE TITLE
(CLI) Deploying containers via a job specification

### ISSUE THREAD

**Issue by XiovV** [XiovV/dokkup#2]
The user should be able to write a configuration file (job specification) for their job and run a command which will execute it.

TODO:
- [x] Load the inventory file
- [x] If there's an `inventory.yaml` file in the same directory load it by default (making the -i or --inventory flag optional in this case)
- [x] Show a summary of the job
- [x] Show node statuses (UP, OFFLINE, API KEY INVALID)
- [x] Show a confirmation message at the bottom of the summary
- [x] Provide a -y flag which will skip the confirmation message
- [x] If a group or nodes are specified, loop through them and run the jobs (concurrently in the future)
- [x] Display the responses coming from the agent in real time (this will show the user what's happening)

Example job specification:
```yaml
group: "dc1" // can be replaced with  'groups' (array), node' (string) or 'nodes' (array)
count: 5

container:
 - name: "test"
   image: "image:latest"
   ports:
   - in: 80
     out: 80
   networks:
    - mynetwork
   volumes:
    - data:/var/lib
   environment: 
    - KEY=VALUE
   restart: always
   labels:
     - "my.label.test=hello"
```

Example job summary:
```
Deployment summary:

NAME   IMAGE          RESTART   COUNT   GROUP   NETWORKS
test   image:latest   always    5       dc1     mynetwork

Node statuses:

NAME    STATUS
node1   ONLINE
node2   OFFLINE
node3   API KEY INVALID

Warning! It seems that there are 2 unavailable nodes, they will be skipped.

Are you sure you want to proceed? (y/n)
```

Example command:
```shell
dokkup run job --inventory inventory.yaml job.yaml
```
