### ISSUE TITLE
(CLI) Inventory file

### ISSUE THREAD

**Issue by XiovV** [XiovV/dokkup#3]
The user should be able to create their own inventory file, which will keep track of their nodes and groups.

 - A node is a single instance where the dokkup agent is running.
 - A group is a group of nodes.

TODO:
- [x] Throw an error if a node that doesn't exist is specified in a group

Example inventory file:
```yaml
nodes:
 - name: "test"
   location: "test"
   key: "abc"
 - name: "test1"
   location: "test"
   key: "abc"

groups:
 - name: "dc1"
   nodes: ["test", "test1"]
```
